--------------------------------------------------------
--  Constraints for Table ASYSCONTENTELEMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("CONTENTTYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("LASTACCESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("CREATEDATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("FILESIZE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("FILEKEY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("VOLUMEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ASYSCONTENTELEMENT" MODIFY ("ELEMENTID" NOT NULL ENABLE);
