--------------------------------------------------------
--  DDL for Table ASYSCONTENTELEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ASYSCONTENTELEMENT" 
   (	"ELEMENTID" CHAR(16 BYTE), 
	"VOLUMEID" VARCHAR2(64 BYTE), 
	"FILEKEY" VARCHAR2(255 BYTE), 
	"FILESIZE" NUMBER(*,0), 
	"CREATEDATE" TIMESTAMP (6), 
	"LASTACCESS" TIMESTAMP (6), 
	"CONTENTTYPE" NUMBER(*,0), 
	"CONTENTCLASSID" CHAR(16 BYTE), 
	"GENERALDATA" VARCHAR2(64 BYTE), 
	"CHECKHINT" NUMBER(*,0), 
	"WRITEDATE" TIMESTAMP (6), 
	"RETENTION" NUMBER(*,0), 
	"CHECKSUM" VARCHAR2(64 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
